services:
  miro:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME}
    privileged: true    
    runtime: nvidia
    network_mode: host
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: bash
    environment:
      # === WSLg / Wayland / Display ===
      DISPLAY: ${DISPLAY:-:0}
      XDG_RUNTIME_DIR: /:/mnt/wslg/runtime-dir
      WAYLAND_DISPLAY: wayland-0

      # === Force NVIDIA D3D12 (Hardware Acceleration) ===
      MESA_LOADER_DRIVER_OVERRIDE: d3d12
      GALLIUM_DRIVER: d3d12
      LIBGL_ALWAYS_SOFTWARE: 0

      # === Wayland + EGL (Suppress DRI2/DRI3 warnings) ===
      GDK_BACKEND: wayland
      EGL_PLATFORM: wayland

      # === Audio via PulseAudio (WSLg) ===
      PULSE_RUNTIME_PATH: /mnt/wslg/runtime-dir/pulse
      PULSE_SERVER: unix:/mnt/wslg/runtime-dir/pulse/native

      # === NVIDIA GPU Passthrough ===
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

    volumes:
      # WSLg runtime (Wayland, Pulse, XWayland)
      - /mnt/wslg/runtime-dir:/mnt/wslg/runtime-dir

      # GPU device
      - /dev/dxg:/dev/dxg

      # MiRo workspace (named volume)
      - mdpv:/root/mdk/catkin_ws/src

    devices:
      - /dev/dxg
      - /dev/snd

    group_add:
      - audio

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  mdpv: