services:
  miro:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME}
    runtime: nvidia
    network_mode: host
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: bash

    environment:
      # === DISPLAY ===
      DISPLAY: :0

      # === WSLg Runtime ===
      XDG_RUNTIME_DIR: /mnt/wslg/runtime-dir
      WAYLAND_DISPLAY: wayland-0

      # === FORCE D3D12 + GLX ===
      MESA_LOADER_DRIVER_OVERRIDE: d3d12
      GALLIUM_DRIVER: d3d12
      LIBGL_ALWAYS_SOFTWARE: 0
      __GLX_VENDOR_LIBRARY_NAME: mesa
      MESA_GL_VERSION_OVERRIDE: 4.6
      MESA_GLSL_VERSION_OVERRIDE: 460

      # === DISABLE DRI & MIT-SHM (CRITICAL) ===
      LIBGL_DRI3_DISABLE: 1
      QT_X11_NO_MITSHM: 1
      GDK_DISABLE_XSHM: 1

      # === X11 FOR GAZEBO ===
      GDK_BACKEND: x11
      QT_QPA_PLATFORM: xcb

      # === AUDIO ===
      PULSE_RUNTIME_PATH: /mnt/wslg/runtime-dir/pulse
      PULSE_SERVER: unix:/mnt/wslg/runtime-dir/pulse/native

      # === NVIDIA ===
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

      # === GAZEBO ===
      GAZEBO_MASTER_URI: http://localhost:11345
      GAZEBO_PLUGIN_PATH: ../bin/deb64:/root/mdk/bin/deb64:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins
      GAZEBO_MODEL_DATABASE_URI: http://models.gazebosim.org
      GAZEBO_RESOURCE_PATH: .:/root/mdk/sim:/usr/share/gazebo-11
      GAZEBO_MODEL_PATH: ./models:/root/mdk/sim/models:/usr/share/gazebo-11/models

    volumes:
      # WSLg runtime
      - /mnt/wslg/runtime-dir:/mnt/wslg/runtime-dir

      # X11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix

      # Xauthority (CRITICAL FOR X CONNECTION)
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:ro

      # GPU
      - /dev/dxg:/dev/dxg

      # Workspace
      - mdpv:/root/mdk/catkin_ws/src

    devices:
      - /dev/dxg
      - /dev/snd

    group_add:
      - audio

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  mdpv: