services:
  miro:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME}
    # hostname: miro  # Actually, no.
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    command: bash
    env_file:
      - .env
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "all"
      PULSE_SERVER: ${PULSE_SERVER}
      PULSE_COOKIE: /root/${PULSE_COOKIE}
    volumes:
      - ${X11UNIX}:${X11UNIX}:rw
      - ${XAUTH}:${XAUTH}:rw
      - ${PULSE_SOCKET}:${PULSE_SOCKET}:rw
      - ${HOME}/${PULSE_COOKIE}:/root/${PULSE_COOKIE}:ro
      - mdpv:/root/mdk/catkin_ws/src
    devices:
      - /dev/snd
    group_add:
      - audio
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  mdpv:
