services:
  miro:
    env_file:
      - .env
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME}
    privileged: true
    network_mode: host
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: bash
    environment:
      # GUI
      DISPLAY: ${DISPLAY}
    volumes:
      # MiRo catkin workspace
      - mdpv:/root/mdk/catkin_ws/src

volumes:
  mdpv:
